

# --------------------------- Custom Configurations ---------------------------

# shell function
fpath=( ${HOME}/.zfunc "${fpath[@]}" )
autoload -U ${HOME}/.zfunc/*(.:t)


# tmux
alias tmux="tmux -u"
