#!/usr/bin/env bash

SCRIPT_DIR="$(cd $(dirname $0); pwd)"

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

if [[ ! -d ${XDG_DATA_HOME:-$HOME/.config/nvim} ]]; then
  mkdir -p ${XDG_DATA_HOME:-$HOME/.config/nvim}
fi

cp $SCRIPT_DIR/init.vim \
  ${XDG_DATA_HOME:-$HOME/.config/nvim/init.vim}

nvim --headless +PlugInstall +qall
