#!/usr/bin/env bash

SCRIPT_DIR="$(cd $(dirname $0); pwd)"

INIT_VIM="${XDG_DATA_HOME:-$HOME/.config/nvim/init.vim}"

for f in $SCRIPT_DIR/plugin_configs/*; do
  plugin_name=$(basename $f | rev | cut -d'.' -f2 | rev)
  if ! grep "\"$plugin_name configuration\"" $INIT_VIM >/dev/null 2>&1; then
    cat $f >> $INIT_VIM
  fi
done

